import { type ComponentType } from 'react';
import {
  HomePage,
  ASN1Page,
  SSLCertificatesPage,
  AESPage,
  DESPage,
  RSAPage,
  ECCPage,
  FPEPage,
  HashPage,
  CharacterEncodingPage,
  BCDPage,
  CheckDigitsPage,
  Base64Page,
  Base94Page,
  MessageParserPage,
  RSADerPublicKeyPage,
  UUIDPage,
  KeyGeneratorPage,
  KeysharePage,
  FuturexKeysPage,
  AtallaKeysPage,
  SafeNetKeysPage,
  ThalesKeysPage,
  ThalesKeyBlockPage,
  TR31Page,
  AS2805Page,
  BitmapPage,
  CVVPage,
  AmexCSCPage,
  MastercardCVC3Page,
  DUKPTPage,
  DUKPTAESPage,
  ISO9797Page,
  ANSIMACPage,
  AS2805MACPage,
  TDESCBCMACPage,
  HMACPage,
  CMACPage,
  RetailMACPage,
  PinBlockGeneralPage,
  PinBlockAESPage,
  PinOffsetPage,
  PinPVVPage,
  VISACertificatesPage,
  ZKAPage,
  PrivacyPolicyPage,
  TermsOfServicePage,
  DisclaimerPage,
  GuidesListPage,
  GuideDetailPage,
} from './routes';

// 路由配置 - 单一数据源
export const routes = [
  { key: 'home', path: '/' },
  { key: 'pki-asn1', path: '/asn1-parser' },
  { key: 'pki-ssl', path: '/ssl-certificates' },
  { key: 'cipher-aes', path: '/aes-encryption' },
  { key: 'cipher-des', path: '/des-encryption' },
  { key: 'cipher-rsa', path: '/rsa-encryption' },
  { key: 'cipher-ecc', path: '/ecc-encryption' },
  { key: 'cipher-fpe', path: '/fpe-encryption' },
  { key: 'generic-hashes', path: '/hashes' },
  { key: 'generic-encoding', path: '/character-encoding' },
  { key: 'generic-bcd', path: '/bcd' },
  { key: 'generic-checkdigits', path: '/check-digits' },
  { key: 'generic-base64', path: '/base64' },
  { key: 'generic-base94', path: '/base94' },
  { key: 'generic-message', path: '/message-parser' },
  { key: 'generic-rsader', path: '/rsa-der-public-key' },
  { key: 'generic-uuid', path: '/uuid' },
  { key: 'keys-dea', path: '/keys-dea' },
  { key: 'keys-keyshare', path: '/keyshare-generator' },
  { key: 'keys-hsm-futurex', path: '/futurex-keys' },
  { key: 'keys-hsm-atalla', path: '/atalla-keys' },
  { key: 'keys-hsm-safenet', path: '/safenet-keys' },
  { key: 'keys-hsm-thales', path: '/thales-keys' },
  { key: 'keys-blocks-thales', path: '/thales-key-block' },
  { key: 'keys-blocks-tr31', path: '/tr31-key-block' },
  { key: 'payments-as2805', path: '/payments-as2805' },
  { key: 'payments-bitmap', path: '/payments-bitmap' },
  { key: 'payments-card-validation-cvvs', path: '/payments-card-validation-cvvs' },
  { key: 'payments-card-validation-amex-cscs', path: '/payments-card-validation-amex-cscs' },
  { key: 'payments-card-validation-mastercard-cvc3', path: '/payments-card-validation-mastercard-cvc3' },
  { key: 'payments-dukpt-iso9797', path: '/payments-dukpt-iso9797' },
  { key: 'payments-dukpt-aes', path: '/payments-dukpt-aes' },
  { key: 'payments-mac-iso9797-1', path: '/payments-mac-iso9797-1' },
  { key: 'payments-mac-ansix9', path: '/payments-mac-ansix9' },
  { key: 'payments-mac-as2805', path: '/payments-mac-as2805' },
  { key: 'payments-mac-tdes-cbc-mac', path: '/payments-mac-tdes-cbc-mac' },
  { key: 'payments-mac-hmac', path: '/payments-mac-hmac' },
  { key: 'payments-mac-cmac', path: '/payments-mac-cmac' },
  { key: 'payments-mac-retail', path: '/payments-mac-retail' },
  { key: 'payments-pin-blocks-general', path: '/payments-pin-blocks-general' },
  { key: 'payments-pin-blocks-aes', path: '/payments-pin-blocks-aes' },
  { key: 'payments-pin-offset', path: '/payments-pin-offset' },
  { key: 'payments-pin-pvv', path: '/payments-pin-pvv' },
  { key: 'payments-visa-certificates', path: '/payments-visa-certificates' },
  { key: 'payments-zka', path: '/payments-zka' },
  { key: 'guides', path: '/guides' },
] as const;

// 路由组件映射 - 用于动态渲染
export const routeComponentMap: Record<string, ComponentType> = {
  '/': HomePage,
  '/asn1-parser': ASN1Page,
  '/ssl-certificates': SSLCertificatesPage,
  '/aes-encryption': AESPage,
  '/des-encryption': DESPage,
  '/rsa-encryption': RSAPage,
  '/ecc-encryption': ECCPage,
  '/fpe-encryption': FPEPage,
  '/hashes': HashPage,
  '/character-encoding': CharacterEncodingPage,
  '/bcd': BCDPage,
  '/check-digits': CheckDigitsPage,
  '/base64': Base64Page,
  '/base94': Base94Page,
  '/message-parser': MessageParserPage,
  '/rsa-der-public-key': RSADerPublicKeyPage,
  '/uuid': UUIDPage,
  '/keys-dea': KeyGeneratorPage,
  '/keyshare-generator': KeysharePage,
  '/futurex-keys': FuturexKeysPage,
  '/atalla-keys': AtallaKeysPage,
  '/safenet-keys': SafeNetKeysPage,
  '/thales-keys': ThalesKeysPage,
  '/thales-key-block': ThalesKeyBlockPage,
  '/tr31-key-block': TR31Page,
  '/payments-as2805': AS2805Page,
  '/payments-bitmap': BitmapPage,
  '/payments-card-validation-cvvs': CVVPage,
  '/payments-card-validation-amex-cscs': AmexCSCPage,
  '/payments-card-validation-mastercard-cvc3': MastercardCVC3Page,
  '/payments-dukpt-iso9797': DUKPTPage,
  '/payments-dukpt-aes': DUKPTAESPage,
  '/payments-mac-iso9797-1': ISO9797Page,
  '/payments-mac-ansix9': ANSIMACPage,
  '/payments-mac-as2805': AS2805MACPage,
  '/payments-mac-tdes-cbc-mac': TDESCBCMACPage,
  '/payments-mac-hmac': HMACPage,
  '/payments-mac-cmac': CMACPage,
  '/payments-mac-retail': RetailMACPage,
  '/payments-pin-blocks-general': PinBlockGeneralPage,
  '/payments-pin-blocks-aes': PinBlockAESPage,
  '/payments-pin-offset': PinOffsetPage,
  '/payments-pin-pvv': PinPVVPage,
  '/payments-visa-certificates': VISACertificatesPage,
  '/payments-zka': ZKAPage,
  '/privacy-policy': PrivacyPolicyPage,
  '/terms-of-service': TermsOfServicePage,
  '/disclaimer': DisclaimerPage,
  '/guides': GuidesListPage,
  '/guides/:slug': GuideDetailPage,
  '/:lang/guides': GuidesListPage,
  '/:lang/guides/:slug': GuideDetailPage,
};

// 生成双向映射
export const routeToKey: Record<string, string> = Object.fromEntries(
  routes.map(r => [r.path, r.key])
);
export const keyToRoute: Record<string, string> = Object.fromEntries(
  routes.map(r => [r.key, r.path])
);

// 路由预加载映射 - 鼠标悬停菜单时提前加载对应 chunk
export const routePrefetchMap: Record<string, () => Promise<unknown>> = {
  'home': () => import('./pages/home/HomePage'),
  'pki-asn1': () => import('./pages/pki/ASN1Page'),
  'pki-ssl': () => import('./pages/pki/SSLCertificatesPage'),
  'cipher-aes': () => import('./pages/cipher/AESPage'),
  'cipher-des': () => import('./pages/cipher/DESPage'),
  'cipher-rsa': () => import('./pages/cipher/RSAPage'),
  'cipher-ecc': () => import('./pages/cipher/ECCPage'),
  'cipher-fpe': () => import('./pages/cipher/FPEPage'),
  'generic-hashes': () => import('./pages/generic/HashPage'),
  'generic-encoding': () => import('./pages/generic/CharacterEncodingPage'),
  'generic-bcd': () => import('./pages/generic/BCDPage'),
  'generic-checkdigits': () => import('./pages/generic/CheckDigitsPage'),
  'generic-base64': () => import('./pages/generic/Base64Page'),
  'generic-base94': () => import('./pages/generic/Base94Page'),
  'generic-message': () => import('./pages/generic/MessageParserPage'),
  'generic-rsader': () => import('./pages/generic/RSADerPublicKeyPage'),
  'generic-uuid': () => import('./pages/generic/UUIDPage'),
  'keys-dea': () => import('./pages/keys/KeyGeneratorPage'),
  'keys-keyshare': () => import('./pages/keys/KeysharePage'),
  'keys-hsm-futurex': () => import('./pages/keys/FuturexKeysPage'),
  'keys-hsm-atalla': () => import('./pages/keys/AtallaKeysPage'),
  'keys-hsm-safenet': () => import('./pages/keys/SafeNetKeysPage'),
  'keys-hsm-thales': () => import('./pages/keys/ThalesKeysPage'),
  'keys-blocks-thales': () => import('./pages/keys/ThalesKeyBlockPage'),
  'keys-blocks-tr31': () => import('./pages/keys/TR31Page'),
  'payments-as2805': () => import('./pages/payment/AS2805Page'),
  'payments-bitmap': () => import('./pages/payment/BitmapPage'),
  'payments-card-validation-cvvs': () => import('./pages/payment/CVVPage'),
  'payments-card-validation-amex-cscs': () => import('./pages/payment/AmexCSCPage'),
  'payments-card-validation-mastercard-cvc3': () => import('./pages/payment/MastercardCVC3Page'),
  'payments-dukpt-iso9797': () => import('./pages/payment/DUKPTPage'),
  'payments-dukpt-aes': () => import('./pages/payment/DUKPTAESPage'),
  'payments-mac-iso9797-1': () => import('./pages/payment/ISO9797Page'),
  'payments-mac-ansix9': () => import('./pages/payment/ANSIMACPage'),
  'payments-mac-as2805': () => import('./pages/payment/AS2805MACPage'),
  'payments-mac-tdes-cbc-mac': () => import('./pages/payment/TDESCBCMACPage'),
  'payments-mac-hmac': () => import('./pages/payment/HMACPage'),
  'payments-mac-cmac': () => import('./pages/payment/CMACPage'),
  'payments-mac-retail': () => import('./pages/payment/RetailMACPage'),
  'payments-pin-blocks-general': () => import('./pages/payment/PinBlockGeneralPage'),
  'payments-pin-blocks-aes': () => import('./pages/payment/PinBlockAESPage'),
  'payments-pin-offset': () => import('./pages/payment/PinOffsetPage'),
  'payments-pin-pvv': () => import('./pages/payment/PinPVVPage'),
  'payments-visa-certificates': () => import('./pages/payment/VISACertificatesPage'),
  'payments-zka': () => import('./pages/payment/ZKAPage'),
};

// 子菜单 key 到其下属路由 key 的映射
export const submenuRouteKeys: Record<string, string[]> = {
  'pki': ['pki-asn1', 'pki-ssl'],
  'generic': ['generic-hashes', 'generic-encoding', 'generic-bcd', 'generic-checkdigits', 'generic-base64', 'generic-base94', 'generic-message', 'generic-rsader', 'generic-uuid'],
  'cipher': ['cipher-aes', 'cipher-des', 'cipher-rsa', 'cipher-ecc', 'cipher-fpe'],
  'keys': ['keys-dea', 'keys-keyshare', 'keys-hsm-futurex', 'keys-hsm-atalla', 'keys-hsm-safenet', 'keys-hsm-thales', 'keys-blocks-thales', 'keys-blocks-tr31'],
  'keys-hsm': ['keys-hsm-futurex', 'keys-hsm-atalla', 'keys-hsm-safenet', 'keys-hsm-thales'],
  'keys-blocks': ['keys-blocks-thales', 'keys-blocks-tr31'],
  'payments': ['payments-as2805', 'payments-bitmap', 'payments-card-validation-cvvs', 'payments-card-validation-amex-cscs', 'payments-card-validation-mastercard-cvc3', 'payments-dukpt-iso9797', 'payments-dukpt-aes', 'payments-mac-iso9797-1', 'payments-mac-ansix9', 'payments-mac-as2805', 'payments-mac-tdes-cbc-mac', 'payments-mac-hmac', 'payments-mac-cmac', 'payments-mac-retail', 'payments-pin-blocks-general', 'payments-pin-blocks-aes', 'payments-pin-offset', 'payments-pin-pvv', 'payments-visa-certificates', 'payments-zka'],
  'payments-card-validation': ['payments-card-validation-cvvs', 'payments-card-validation-amex-cscs', 'payments-card-validation-mastercard-cvc3'],
  'payments-dukpt': ['payments-dukpt-iso9797', 'payments-dukpt-aes'],
  'payments-mac-algorithms': ['payments-mac-iso9797-1', 'payments-mac-ansix9', 'payments-mac-as2805', 'payments-mac-tdes-cbc-mac', 'payments-mac-hmac', 'payments-mac-cmac', 'payments-mac-retail'],
  'payments-pin-blocks': ['payments-pin-blocks-general', 'payments-pin-blocks-aes'],
};

// 预加载路由
export const prefetchRoute = (key: string): void => {
  const fn = routePrefetchMap[key];
  if (fn) fn();
};

// 预加载子菜单路由
export const prefetchSubmenuRoutes = (submenuKey: string): void => {
  const keys = submenuRouteKeys[submenuKey];
  if (keys) {
    keys.forEach(prefetchRoute);
  }
};
